# Generated by Django 5.2.13 on 2026-04-11 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_topic_unit_ticket_priority_ticket_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.unit'),
        ),
    ]
